# Generated by Django 4.2.1 on 2023-10-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cartitem_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='attribute1',
            field=models.CharField(choices=[('TT', 'Texas Tea'), ('FR', 'Fiesta Red'), ('CB', 'Cobalt Blue')], max_length=64),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='attribute2',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(max_length=75),
        ),
    ]
