# Generated by Django 4.2.6 on 2023-11-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_cartitem_attribute1_alter_cartitem_attribute2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo_name',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
