# Generated by Django 4.2.7 on 2023-11-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_photo_name_product_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photo',
            new_name='photo1',
        ),
        migrations.AddField(
            model_name='product',
            name='photo2',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo3',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
